### ISSUE TITLE
https://localhost:8082 does not respond

### ISSUE THREAD

**Issue by jasonsultana** [ConsumerDataStandardsAustralia/dsb-test-data#18]
Hello,

I've followed the instructions under `Local Setup and Customisation` in the project read me, and I can access most of the applications, eg port 9001, 8001 after running `docker-compose up`. But localhost:8082 responds with `ERR_CONNECTION_CLOSED`. 

In fact, looking at the `docker-compose.yaml` file, it has `mock-data-holder` running under port 3005, which does respond. Is the documentation out of date (with 8082 being an old port) or am I mis-understanding something? I can see port 8082 assigned to `mtls-gateway`.

Thanks heaps.

**Comment by tom-schier** [comment]
@jasonsultana the port 3005 is in fact exposed. This is because this is a development system. In a production system you would receive all calls via a gateway, which then redirects the call as per gatewayconfig.json.
Could you provide some more information on the replication steps? In particular, what is the exact url you are calling? The error you mention suggest some sort of SSL issue.
